/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomAside: typeof import('./components/CustomAside/Index.vue')['default']
    CustomHeader: typeof import('./components/CustomHeader/Index.vue')['default']
    CustomMain: typeof import('./components/CustomMain/Index.vue')['default']
    EventCard: typeof import('./components/EventCard/Index.vue')['default']
    EventCardDesktopMenu: typeof import('./components/EventCard/DesktopMenu/Index.vue')['default']
    EventCardMobileMenu: typeof import('./components/EventCard/MobileMenu/Index.vue')['default']
    EventSecondaryPage: typeof import('./components/EventSecondaryPage/index.vue')['default']
    LoginForm: typeof import('./components/LoginForm/Index.vue')['default']
    MainGrid: typeof import('./components/MainGrid/Index.vue')['default']
    MainStone: typeof import('./components/MainStone/Index.vue')['default']
    MainStoneAccentBox: typeof import('./components/MainStone/AccentBox/Index.vue')['default']
    MainStoneMainDataBox: typeof import('./components/MainStone/MainDataBox/Index.vue')['default']
    MainStoneMainDataBoxMobile: typeof import('./components/MainStone/MainDataBoxMobile/Index.vue')['default']
    MainStoneTabPanelContent: typeof import('./components/MainStone/TabPanelContent/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallSectionLayout: typeof import('./components/SmallSectionLayout/Index.vue')['default']
    UIButton: typeof import('./components/UI/Button.vue')['default']
    UIContainer: typeof import('./components/UI/Container.vue')['default']
    UIProgressCircular: typeof import('./components/UI/ProgressCircular.vue')['default']
    UITextInputField: typeof import('./components/UI/TextInputField.vue')['default']
    VisaAssistancePage: typeof import('./components/VisaAssistancePage/index.vue')['default']
  }
}
