/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LayoutAside: typeof import('./components/Layout/Aside/Index.vue')['default']
    LayoutEventCard: typeof import('./components/Layout/EventCard/Index.vue')['default']
    LayoutHeader: typeof import('./components/Layout/Header/Index.vue')['default']
    LayoutMain: typeof import('./components/Layout/Main/Index.vue')['default']
    LayoutMainGrid: typeof import('./components/Layout/MainGrid/Index.vue')['default']
    LayoutMainListOfPages: typeof import('./components/Layout/Main/ListOfPages/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIButton: typeof import('./components/UI/Button.vue')['default']
    UIContainer: typeof import('./components/UI/Container.vue')['default']
    UIProgressCircular: typeof import('./components/UI/ProgressCircular.vue')['default']
  }
}
